### ISSUE TITLE
`ERR_OSSL_EVP_UNSUPPORTED` on `npm start`

### ISSUE THREAD

**Issue by turbinenreiter** [asyncapi/studio#360]
#### Describe the bug

Starting the studio fails with:

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/studio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/studio/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/studio/node_modules/webpack/lib/NormalModule.js:471:10)
    at /studio/node_modules/webpack/lib/NormalModule.js:503:5
    at /studio/node_modules/webpack/lib/NormalModule.js:358:12
    at /studio/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/studio/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/studio/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/studio/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/studio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/studio/node_modules/webpack/lib/NormalModule.js:417:16)
    at /studio/node_modules/webpack/lib/NormalModule.js:452:10
    at /studio/node_modules/webpack/lib/NormalModule.js:323:13
    at /studio/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /studio/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/studio/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /studio/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

#### How to Reproduce

Run

`npm install`

`npm start`

on Fedora 36 with node v16.14.0.

#### Expected behavior

I expected the studio to start.

**Comment by magicmatatjahu** [comment]
@turbinenreiter Hello! Thanks for the issue. Could you try to run `start` script by exporting given env?

```
export NODE_OPTIONS=--openssl-legacy-provider
```

or try this one https://roytuts.com/how-to-fix-err_ossl_evp_unsupported-in-react-js-application/

Let us know what fix help you and we will try to propagate it in project.

**Comment by turbinenreiter** [comment]
`--openssl-legacy-provider` did not help.

**Comment by magicmatatjahu** [comment]
@turbinenreiter Any update?

**Comment by magicmatatjahu** [comment]
Closing due to lack of feedback.

**Comment by magicmatatjahu** [comment]
@aeworxet has similar problem.

**Comment by aeworxet** [comment]
This error will appear again as more and more users transition to Node.js v17+.
```
This error is because node.js 17 uses OpenSSL3, which has changed code for
initialization context of md family (including md4), and this is a breaking change.
```
https://itsmycode.com/error-digital-envelope-routines-unsupported

The approach with
```bash
export NODE_OPTIONS=--openssl-legacy-provider
```
works but I would still prefer to modify `package.json` with
```diff
- "start": "cross-env DISABLE_ESLINT_PLUGIN=true craco start",
+ "start": "cross-env DISABLE_ESLINT_PLUGIN=true craco --openssl-legacy-provider start",
```
to keep users from frustration and continue uninterruptable shipping of a fully-fledged product.

**Comment by magicmatatjahu** [comment]
@aeworxet Could you create PR? We will be glad for it :)

**Comment by magicmatatjahu** [comment]
You can also pass env like:

```
cross-env DISABLE_ESLINT_PLUGIN=true NODE_OPTIONS=--openssl-legacy-provider craco start
```
